// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifbuptqigflkgvnacord.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmYnVwdHFpZ2Zsa2d2bmFjb3JkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2NTQxNzcsImV4cCI6MjA1MTIzMDE3N30.IzAl9-j2kB1NFh87gOulVt3N71apdSd7PqurZrrI9tk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);